### ISSUE TITLE
Consolidate projects into a collection

### ISSUE THREAD

**Issue by ptkinvent** [ptkinvent/ptkinvent.github.io#19]
Jekyll supports collections of items and auto-generation of templates in a for-loop. The projects on the homepage should be done in this manner. In case I forget, it works as follows:

 1. In _config.yml, insert the following:
    ```yaml
    # Collections
    collections:
      projects:
        output: true # This line means auto-generate a page for each project
    ```
    Note that you'll have to restart `jekyll serve` because _config.yml was updated.
 2. Create directory at the top level called `_projects/` and move all project HTML files into it.
 3. On the homepage, you can now iterate over the projects like this:
    ```html
    {% for project in site.projects %|
    <h1>{{ project.title }}</h1>
    {% endfor %}
    ```

This will lead to a cleaner directory layout, less repeated code, and better extensibility in the future.
